### ISSUE TITLE
Heroku好像开始封杀v2ray了 

### ISSUE THREAD

**Issue by zx3777** [xuiv/v2ray-heroku#1]

**Comment by xuiv** [comment]
可以试试gost-heroku

**Comment by zx3777** [comment]
我看了您的gost-heroku教程，部署完以后，到了第二步“本地客户端执行：gost -L=:1080 -F=ss+wss://aes-128-cfb:1234567890@xxxxx.herokuapp.com:443”，就不会了。我下了官方的二进制客户端，只有一个gost.exe,而且打开还是一闪而过，不知道怎么操作，网上的教程少之又少，能指导我一下吗？谢谢

**Comment by xuiv** [comment]
建立一个bat或cmd或vbs文件，保证gost.exe在可执行路径内，vbs文件内容如下：
createobject("wscript.shell").run "gost -L=:1080 -F=ss+wss://aes-128-cfb:1234567890@xxxxx.herokuapp.com:443",0

**Comment by zx3777** [comment]
十分感谢！
polaris <notifications@github.com> 于2018年9月12日周三 上午10:57写道：
